### ISSUE TITLE
sync from Thunderbird to Google always deletes anything that doesn't exist in Google

### ISSUE THREAD

**Issue by f1lterr** [zanonmark/Google-4-TbSync#27] opened 2021-11-28 17:16 UTC
Hi,

I understand that unchecking "Read Only" is "at your own risk" and have read the wiki post for former gContact users. 

Even if I start with an empty Google Contacts, then enable sync, no matter what I do, (readonly checked OR unchecked) any contact I add in Thunderbird is deleted from Thunderbird when I sync. 

Is this the current, expected behavior and should I really consider this tool to be a one way sync from Google to Thunderbird at present?

Thanks for working on this extension - much appreciated!

-Steve

**Comment by zanonmark** [comment] 2022-01-07 12:26
Hi Steve, sorry for the delay in answering.

Well,
a) this is the expected behaviour if You check the "Read-only mode" flag (any local contact not existing on the Google side will be deleted),
b) this is NOT the expected behaviour if the "Read-only mode" flag is unchecked: in this case, the local contact should be pushed to Google too.

Could You please update all of Your softwares, especially TbSync and Google-4-TbSync, to their latest versions and tell me if this happens again?
In which case, we will have to investigate deeper...

Thanks,
MZ

**Comment by zanonmark** [comment] 2022-02-25 08:52
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ

**Closed by zanonmark** 2022-02-25 08:52 UTC
Labels: bug, question
