### ISSUE TITLE
Thunderbird update

### ISSUE THREAD

**Issue by naasking** [zanonmark/Google-4-TbSync#24] opened 2021-10-19 13:41 UTC
Thunderbird just updated to 91.2.0 on me and TbSync for google contacts no longer seems to work. It keeps saying that I need to install CalDAV & CardDAV, but it's already installed. I've been running TbSync for years at this point, so this is definitely related to the update that just happened.

I tried disabling/enabling addons, no luck. I even tried deleting my TbSync Google account and setting it up from scratch, same problem as above. Any suggestions would be welcome!

**Comment by Silbad** [comment] 2021-11-04 09:03
Hello, same for me, Google-4-TbSync crash Thunderbird each time it launch the sync... Thanks

**Comment by zanonmark** [comment] 2021-11-06 15:20
Hi,

@naasking: It was probably a temporary failure, as I'm running TB 91.3.0 + TbSync 3.0.1 + Google-4-TbSync 0.2.1 now and everything works. Maybe, during the TB upgrade, some packages went out-of-sync.
So I'm closing this issue, but feel free to reopen it if it persists.

@Silbad: This seems a duplicate of #22, please let's continue this specific discussion on that page.

Thanks,
MZ

**Closed by zanonmark** 2021-11-06 15:20 UTC

**Comment by naasking** [comment] 2021-11-10 12:38
Hey MZ, yes updating some of the addons corrected it, but now CalDAV & CardDAV asks for my Google login every time Thunderbird opens, and doesn't save it even when "don't ask again on this device" is clicked. I believe this started happening after another recent Thunderbird update. I'm now on 91.3.0, TbSync 3.0.1, CalDav 2.0.2, Google-4-TbSync 0.2.1
